# Generated by Django 4.2.4 on 2023-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='', max_length=40)),
                ('description_food', models.CharField(default='', max_length=100)),
                ('date_delivery', models.DateField()),
                ('fresh', models.BooleanField(default='not fresh', verbose_name='fresh')),
            ],
        ),
    ]
