# Generated by Django 4.2.4 on 2023-09-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_donation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetail',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='fooddetail',
            name='date_delivery',
            field=models.DateField(auto_created=True),
        ),
    ]
